// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEo76w5aqRApVinlsmDFiCKNmnnsLIFig',
    appId: '1:783612012492:web:ef989bc912e6f8cce25f69',
    messagingSenderId: '783612012492',
    projectId: 'store-dc4d9',
    authDomain: 'store-dc4d9.firebaseapp.com',
    storageBucket: 'store-dc4d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTzYBRmzN7YB2toNiDNoFoL-jxcAFYzE',
    appId: '1:783612012492:android:51348814336a1025e25f69',
    messagingSenderId: '783612012492',
    projectId: 'store-dc4d9',
    storageBucket: 'store-dc4d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7pYn6hfG0VEngiH4tb576PhMRoWmDvUk',
    appId: '1:783612012492:ios:6a5429a710060075e25f69',
    messagingSenderId: '783612012492',
    projectId: 'store-dc4d9',
    storageBucket: 'store-dc4d9.appspot.com',
    androidClientId: '783612012492-51rbum7g9as6pgsi6iitvkmlg7sl45q0.apps.googleusercontent.com',
    iosClientId: '783612012492-ssoe2cb0g03d5846lerf1od1v6iqo2rm.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7pYn6hfG0VEngiH4tb576PhMRoWmDvUk',
    appId: '1:783612012492:ios:6a5429a710060075e25f69',
    messagingSenderId: '783612012492',
    projectId: 'store-dc4d9',
    storageBucket: 'store-dc4d9.appspot.com',
    androidClientId: '783612012492-51rbum7g9as6pgsi6iitvkmlg7sl45q0.apps.googleusercontent.com',
    iosClientId: '783612012492-ssoe2cb0g03d5846lerf1od1v6iqo2rm.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEo76w5aqRApVinlsmDFiCKNmnnsLIFig',
    appId: '1:783612012492:web:6d8970ce55f3effde25f69',
    messagingSenderId: '783612012492',
    projectId: 'store-dc4d9',
    authDomain: 'store-dc4d9.firebaseapp.com',
    storageBucket: 'store-dc4d9.appspot.com',
  );

}